"use client";

import { useState } from "react";
import { setLang } from "@/lib/compliance/i18n";

const L: Record<string, { en: string; zh: string }> = {
  title: { en: "Terms of Service", zh: "服务协议" },
  updated: { en: "Last updated: July 24, 2026", zh: "最后更新：2026年7月24日" },
  back: { en: "← Back", zh: "← 返回" },
  s1: { en: "1. Service Nature", zh: "1. 服务性质" },
  s1Body: { en: "clausr.ai is an AI-assisted compliance assessment tool. It provides regulatory analysis, gap assessment, and document generation to assist organizations in evaluating products and documents against applicable standards. clausr.ai is not a substitute for professional legal advice, certified testing, or formal certification decisions.", zh: "clausr.ai 是一款AI辅助合规评估工具，提供法规分析、差距评估和文档生成功能，协助组织对产品和文档进行标准合规评估。clausr.ai 不替代专业法律意见、认证测试或正式的认证决策。" },
  s2: { en: "2. User Eligibility", zh: "2. 用户资格" },
  s2Body: { en: "This service is NOT for minors. Minors (individuals under 18) may not register or use this service. The service is intended for registered professionals and enterprises, including compliance officers, legal professionals, and product managers. By registering, you confirm that you are 18 or older and meet these eligibility requirements.", zh: "本服务不面向未成年人。未成年人（未满18周岁）不得注册使用本服务。本服务面向注册专业人士及企业，包括合规官、法律人士和产品经理。注册即表示您确认已年满18周岁且符合上述资格要求。" },
  s3: { en: "3. AI-Generated Content Disclaimer", zh: "3. AI生成内容免责声明" },
  s3Body: { en: "The outputs generated by clausr.ai are produced by large language models (LLMs) and may contain errors, omissions, or inaccuracies. All AI-generated content is labeled with a clausr.ai badge. Users must independently verify all critical compliance decisions with qualified professionals. clausr.ai and its operators disclaim all liability for decisions made based on AI-generated outputs.", zh: "clausr.ai 生成的内容由大语言模型（LLM）产生，可能存在错误、遗漏或不准确之处。所有AI生成内容均标注 clausr.ai 标识。用户应自行验证关键合规决策，必要时咨询合格专业人士。clausr.ai 及其运营方不对基于AI生成内容做出的决策承担任何责任。" },
  s4: { en: "4. Intellectual Property & Copyright Risk", zh: "4. 知识产权与版权风险" },
  s4Body: { en: "AI-generated content may inadvertently incorporate or resemble copyrighted material. clausr.ai does not warrant that generated content does not infringe third-party intellectual property rights. Users should conduct independent IP due diligence before using generated content in commercial contexts. Users retain rights to their input data and uploaded files.", zh: "AI生成内容可能无意中包含或模仿受版权保护的材料。clausr.ai 不保证生成内容不侵犯第三方知识产权。用户在商业场景中使用生成内容前应进行独立的知识产权尽职调查。用户对其输入数据和上传文件保留所有权。" },
  s5: { en: "5. Data Usage & Privacy", zh: "5. 数据使用与隐私" },
  s5Body: { en: "Messages and uploaded files are sent to third-party LLM providers solely for generating compliance assessments. User input is not used for model training or fine-tuning. Data retention is configurable per organization (default 90 days). Users may request data deletion at tianjierong@inspectorai.cn. See the Disclosure page for full details.", zh: "消息和上传文件仅发送至第三方LLM提供者用于生成合规评估。用户输入不用于模型训练或微调。数据保留期按组织配置（默认90天）。用户可通过 tianjierong@inspectorai.cn 请求删除数据。详情请参阅透明度公开页面。" },
  s6: { en: "6. Limitation of Liability", zh: "6. 责任限制" },
  s6Body: { en: "To the maximum extent permitted by applicable law, clausr.ai and its operators shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from the use of or inability to use the service, including but not limited to certification failures, regulatory penalties, or business losses. The service is provided \"as is\" without any warranty, express or implied.", zh: "在适用法律允许的最大范围内，clausr.ai 及其运营方不对因使用或无法使用本服务产生的任何直接、间接、附带、特殊或后果性损害承担责任，包括但不限于认证失败、监管处罚或业务损失。本服务按\"现状\"提供，不作任何明示或暗示的保证。" },
  s7: { en: "7. Prohibited Conduct", zh: "7. 禁止行为" },
  s7Body: { en: "Users shall not: (a) attempt to bypass content safety filters or inject malicious prompts; (b) use the service to generate false or fraudulent compliance documents; (c) upload malware or unauthorized copyrighted material; (d) violate any applicable laws or regulations. Violation may result in immediate termination of access without notice.", zh: "用户不得：(a) 尝试绕过内容安全过滤或注入恶意提示；(b) 使用本服务生成虚假或欺诈性合规文件；(c) 上传恶意软件或未经授权的受版权保护材料；(d) 违反任何适用法律法规。违规可能导致立即终止访问权限，恕不另行通知。" },
  s8: { en: "8. Amendments", zh: "8. 协议修改" },
  s8Body: { en: "We reserve the right to modify these terms at any time. Material changes will be communicated via email or in-app notice. Continued use after changes take effect constitutes acceptance of the revised terms.", zh: "我们保留随时修改本协议的权利。重大变更将通过邮件或应用内通知告知。变更生效后继续使用即视为接受修订后的协议。" },
};

export default function TermsPage() {
  const [lang, setLangState] = useState("zh");

  const toggleLang = () => {
    const next = lang === "zh" ? "en" : "zh";
    setLangState(next);
    setLang(next as "en" | "zh");
  };

  const l = (k: string) => {
    const e = L[k];
    return e ? e[lang as keyof typeof e] ?? e.zh : k;
  };

  const sec = (title: string, body: string) => (
    <div style={{ marginBottom: 12, padding: "14px 18px", borderRadius: 8, border: "1px solid var(--color-border-default)", background: "var(--color-bg-card)" }}>
      <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 6, color: "var(--color-text-heading)" }}>{title}</div>
      <p style={{ fontSize: 14, lineHeight: 1.6, color: "var(--color-text-body)", margin: 0 }}>{body}</p>
    </div>
  );

  return (
    <div style={{ maxWidth: 640, padding: "12px 20px 40px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
        <button onClick={() => window.history.back()}
          style={{ padding: "4px 10px", borderRadius: 4, border: "1px solid var(--color-border-default)", background: "transparent", cursor: "pointer", fontSize: 12, color: "var(--color-text-muted)" }}>
          {l("back")}
        </button>
        <button onClick={toggleLang}
          style={{ padding: "3px 8px", borderRadius: 4, border: "1px solid var(--color-border-default)", background: "var(--color-bg-dark)", cursor: "pointer", fontSize: 10, fontWeight: 600, color: "var(--color-text-muted)" }}>
          {lang === "zh" ? "EN" : "中文"}
        </button>
      </div>
      <h1 style={{ fontSize: 22, fontWeight: 700, margin: "0 0 2px", color: "var(--color-text-heading)" }}>{l("title")}</h1>
      <p style={{ fontSize: 12, color: "var(--color-text-muted)", marginBottom: 16 }}>{l("updated")}</p>
      {sec(l("s1"), l("s1Body"))}
      {sec(l("s2"), l("s2Body"))}
      {sec(l("s3"), l("s3Body"))}
      {sec(l("s4"), l("s4Body"))}
      {sec(l("s5"), l("s5Body"))}
      {sec(l("s6"), l("s6Body"))}
      {sec(l("s7"), l("s7Body"))}
      {sec(l("s8"), l("s8Body"))}
    </div>
  );
}
