import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, Header, Footer, PageNumber, BorderStyle,
} from "docx";
import * as fs from "fs";
import * as path from "path";

const FIELDS: { id: string; label: string }[] = [
  { id: "dataClassification", label: "Data Classification and Grading Scheme" },
  { id: "securityOrganization", label: "Data Security Organization and Responsibilities" },
  { id: "securitySystem", label: "Data Security Policies and Procedures" },
  { id: "dataLifecycleMgmt", label: "Data Lifecycle Security Management" },
  { id: "technicalProtection", label: "Technical Protection Measures" },
  { id: "riskAssessment", label: "Data Security Risk Assessment" },
  { id: "incidentResponse", label: "Data Security Incident Response Plan" },
  { id: "capacityEvaluation", label: "DSMM Capability Maturity Self-Evaluation" },
];

const BRAND_BLUE = "2563EB";
const GRAY = "6B7280";
const LIGHT_GRAY = "9CA3AF";

const children: Paragraph[] = [];

// Title
children.push(new Paragraph({
  text: "GB/T 44464 — DSMM Data Security Documentation",
  heading: HeadingLevel.HEADING_1,
  alignment: AlignmentType.CENTER,
  spacing: { after: 100 },
}));

// Brand line
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { after: 200 },
  children: [
    new TextRun({ text: "Generated by ", size: 20, color: LIGHT_GRAY }),
    new TextRun({ text: "clausr.ai", size: 20, color: BRAND_BLUE, bold: true }),
    new TextRun({ text: " Compliance Engine", size: 20, color: LIGHT_GRAY }),
  ],
}));

// Separator
children.push(new Paragraph({
  spacing: { after: 300 },
  border: { bottom: { color: "E5E7EB", size: 6, style: BorderStyle.SINGLE, space: 1 } },
}));

// Meta
children.push(new Paragraph({
  spacing: { after: 100 },
  children: [
    new TextRun({ text: "Document: ", bold: true, size: 22 }),
    new TextRun({ text: "DSMM Data Security Documentation", size: 22 }),
  ],
}));

children.push(new Paragraph({
  spacing: { after: 100 },
  children: [
    new TextRun({ text: "Standard: ", bold: true, size: 22 }),
    new TextRun({ text: "GB/T 44464 — Data Security Capability Maturity Model", size: 22 }),
  ],
}));

children.push(new Paragraph({
  spacing: { after: 400 },
  children: [
    new TextRun({ text: "Date: ", bold: true, size: 22 }),
    new TextRun({ text: "{generationDate}", size: 22, color: GRAY, italics: true }),
  ],
}));

// Section heading
children.push(new Paragraph({
  text: "Assessment Fields",
  heading: HeadingLevel.HEADING_2,
  spacing: { before: 400, after: 200 },
}));

// Instruction
children.push(new Paragraph({
  spacing: { after: 300 },
  children: [
    new TextRun({ text: "The following sections document the organization\u2019s DSMM compliance status across all assessment dimensions.", size: 20, color: GRAY, italics: true }),
  ],
}));

// Fields section
for (let i = 0; i < FIELDS.length; i++) {
  const f = FIELDS[i];

  // Field label as a heading-like line
  children.push(new Paragraph({
    spacing: { before: 300, after: 40 },
    border: { left: { color: BRAND_BLUE, size: 12, style: BorderStyle.SINGLE, space: 8 } },
    children: [
      new TextRun({ text: `${i + 1}. ${f.label}`, bold: true, size: 22, color: "1F2937" }),
    ],
  }));

  // Placeholder for the field value
  children.push(new Paragraph({
    spacing: { after: 200 },
    indent: { left: 360 },
    children: [
      new TextRun({ text: `{${f.id}}`, size: 22, color: GRAY, italics: true }),
    ],
  }));
}

// Signature block
children.push(new Paragraph({
  spacing: { before: 600, after: 100 },
  border: { top: { color: "E5E7EB", size: 6, style: BorderStyle.SINGLE, space: 1 } },
}));

children.push(new Paragraph({
  spacing: { before: 200 },
  alignment: AlignmentType.CENTER,
  children: [
    new TextRun({ text: "This document was generated by ", size: 18, color: LIGHT_GRAY }),
    new TextRun({ text: "clausr.ai", size: 18, color: BRAND_BLUE, bold: true }),
    new TextRun({ text: " Compliance Assessment Engine", size: 18, color: LIGHT_GRAY }),
  ],
}));

children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { after: 100 },
  children: [
    new TextRun({ text: "© 2026 clausr.ai \u2014 DSMM Compliance Assessment", size: 18, color: LIGHT_GRAY }),
  ],
}));

children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  children: [
    new TextRun({ text: "Generated on: ", size: 16, color: LIGHT_GRAY }),
    new TextRun({ text: "{generationDate}", size: 16, color: LIGHT_GRAY }),
  ],
}));

const doc = new Document({
  title: "GB/T 44464 — DSMM Data Security Documentation",
  description: "Generated by clausr.ai Compliance Engine",
  styles: {
    default: {
      document: {
        run: { font: "Calibri", size: 22 },
        paragraph: { spacing: { after: 100 } },
      },
    },
  },
  sections: [{
    headers: {
      default: new Header({
        children: [
          new Paragraph({
            alignment: AlignmentType.RIGHT,
            border: { bottom: { color: "E5E7EB", size: 4, style: BorderStyle.SINGLE, space: 4 } },
            children: [
              new TextRun({ text: "clausr.ai", bold: true, size: 18, color: BRAND_BLUE }),
              new TextRun({ text: "  |  GB/T 44464 DSMM", size: 18, color: LIGHT_GRAY }),
            ],
          }),
        ],
      }),
    },
    footers: {
      default: new Footer({
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            border: { top: { color: "E5E7EB", size: 4, style: BorderStyle.SINGLE, space: 4 } },
            children: [
              new TextRun({ text: "Page ", size: 16, color: LIGHT_GRAY }),
              new TextRun({ children: [PageNumber.CURRENT], size: 16, color: LIGHT_GRAY }),
              new TextRun({ text: " of ", size: 16, color: LIGHT_GRAY }),
              new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: LIGHT_GRAY }),
              new TextRun({ text: "  |  Generated by clausr.ai", size: 16, color: LIGHT_GRAY }),
            ],
          }),
        ],
      }),
    },
    children,
  }],
});

const buffer = await Packer.toBuffer(doc);
const outputPath = path.resolve("../../../raipple-saas/apps/clausr/packs/datasec-gb44464/template.docx");
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, buffer);
console.log(`Template written to ${outputPath} (${buffer.length} bytes)`);
