import { describe, it, expect, vi, beforeEach } from "vitest";

const { mockInitSession } = vi.hoisted(() => ({ mockInitSession: vi.fn() }));
vi.mock("../loading/phases/init-phase", () => ({
  initSession: mockInitSession,
}));

const { mockInputPhase } = vi.hoisted(() => ({ mockInputPhase: vi.fn() }));
vi.mock("../loading/phases/input-phase", () => ({
  inputPhase: mockInputPhase,
}));

const { mockGenerateStepsFromChecks } = vi.hoisted(() => ({ mockGenerateStepsFromChecks: vi.fn() }));
vi.mock("../loading/generate-steps", () => ({
  generateStepsFromChecks: mockGenerateStepsFromChecks,
}));

const { mockCreatePipelineContext, mockRestoreContext } = vi.hoisted(() => ({
  mockCreatePipelineContext: vi.fn(),
  mockRestoreContext: vi.fn(),
}));
vi.mock("../pipeline/pipeline-context", () => ({
  createPipelineContext: mockCreatePipelineContext,
  restoreContext: mockRestoreContext,
}));

const { mockGenerateCorrelationId } = vi.hoisted(() => ({
  mockGenerateCorrelationId: vi.fn(() => "corr-loading-001"),
}));
vi.mock("../pipeline/errors", () => ({
  generateCorrelationId: mockGenerateCorrelationId,
}));

const { mockSaveSessionSetup, mockLoadSessionSetup } = vi.hoisted(() => ({
  mockSaveSessionSetup: vi.fn(),
  mockLoadSessionSetup: vi.fn(),
}));
vi.mock("../shared/memory/repository", () => ({
  saveSessionSetup: mockSaveSessionSetup,
  loadSessionSetup: mockLoadSessionSetup,
}));

const { mockLogPipeline } = vi.hoisted(() => ({ mockLogPipeline: vi.fn() }));
vi.mock("../pipeline/logger", () => ({
  logPipeline: mockLogPipeline,
}));

import { setupSkill, processSessionFiles } from "../loading/loading-orchestrator";

describe("loading-orchestrator", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("setupSkill", () => {
    it("loads skill, creates context, generates steps, and persists", async () => {
      const checks = [
        { field: "mounting_height", type: { kind: "number" }, description: "Check height", clause: "R48.6.2", attention: "height", sample: "650 mm", dependsOn: undefined },
      ];
      const steps = [{ number: 1, title: "mounting_height", instructions: "Check", type: "llm+tool" }];

      mockInitSession.mockResolvedValue({
        skill: { name: "test-skill", checks, scripts: [], regulationIds: ["R48"], skillmd: "# Skill", description: "Test", triggers: [] },
        isAutoSkill: false,
      });

      const mockCtx = {
        skill: { name: "test-skill", checks, scripts: [], regulationIds: ["R48"], skillmd: "# Skill\n\n> Auto-generated by clausr.ai" },
        files: { toJSON: vi.fn().mockReturnValue([]) },
        correlationId: "corr-001",
      };
      mockCreatePipelineContext.mockReturnValue(mockCtx);
      mockGenerateStepsFromChecks.mockReturnValue(steps);

      const correlationId = await setupSkill("session-1", "test-skill");

      expect(correlationId).toBe("corr-loading-001");
      expect(mockInitSession).toHaveBeenCalledWith("test-skill", "session-1", undefined, undefined, undefined);
      expect(mockCreatePipelineContext).toHaveBeenCalled();
      expect(mockGenerateStepsFromChecks).toHaveBeenCalledWith(checks, ["R48"]);

      expect(mockSaveSessionSetup).toHaveBeenCalledWith("session-1", {
        skillName: "test-skill",
        skillmd: expect.stringContaining("Auto-generated"),
        checks,
        scripts: [],
        regulationIds: ["R48"],
        steps,
        fileRegistry: [],
      });
    });

    it("accepts optional tenant/user params", async () => {
      const checks: never[] = [];
      mockInitSession.mockResolvedValue({
        skill: { name: "tenant-skill", checks, scripts: [], regulationIds: [], skillmd: "# Skill", description: "", triggers: [] },
        isAutoSkill: false,
      });
      mockCreatePipelineContext.mockReturnValue({
        skill: { name: "tenant-skill", checks, scripts: [], regulationIds: [], skillmd: "# Skill" },
        files: { toJSON: vi.fn().mockReturnValue([]) },
      });
      mockGenerateStepsFromChecks.mockReturnValue([]);

      await setupSkill("session-2", "tenant-skill", { tenantId: "t1", userId: "u1", userEmail: "u@t.com" });

      expect(mockInitSession).toHaveBeenCalledWith("tenant-skill", "session-2", "t1", "u1", "u@t.com");
    });

    it("handles empty checks gracefully", async () => {
      mockInitSession.mockResolvedValue({
        skill: { name: "empty-skill", checks: [], scripts: [], regulationIds: [], skillmd: "# Empty", description: "", triggers: [] },
        isAutoSkill: false,
      });
      mockCreatePipelineContext.mockReturnValue({
        skill: { name: "empty-skill", checks: [], scripts: [], regulationIds: [], skillmd: "# Empty" },
        files: { toJSON: vi.fn().mockReturnValue([]) },
      });
      mockGenerateStepsFromChecks.mockReturnValue([]);

      const correlationId = await setupSkill("session-3", "empty-skill");
      expect(correlationId).toBeTruthy();
      expect(mockSaveSessionSetup).toHaveBeenCalled();
    });
  });

  describe("processSessionFiles", () => {
    it("is no-op when files array is empty", async () => {
      await processSessionFiles({ sessionId: "session-1", files: [] });
      expect(mockLoadSessionSetup).not.toHaveBeenCalled();
    });

    it("warns when no setup found", async () => {
      mockLoadSessionSetup.mockReturnValue(null);
      await processSessionFiles({ sessionId: "session-1", files: [{ name: "doc.pdf", size: 100, type: "application/pdf", dataUrl: "data:base64," }] });
      expect(mockLogPipeline).toHaveBeenCalledWith(expect.stringContaining("no setup found"));
      expect(mockInputPhase).not.toHaveBeenCalled();
    });

    it("processes files and updates registry", async () => {
      const existingRegistry = [{ filename: "existing.pdf", fileId: "existing" }];
      const newFileEntry = { filename: "doc.pdf", fileId: "doc.pdf", extractedText: "content" };

      mockLoadSessionSetup.mockReturnValue({
        skillName: "test-skill",
        skillmd: "# Skill",
        checks: [],
        scripts: [],
        regulationIds: [],
        steps: [],
        fileRegistry: existingRegistry,
      });

      mockCreatePipelineContext.mockReturnValue({
        skill: { name: "test-skill", checks: [], scripts: [], regulationIds: [], skillmd: "# Skill" },
        files: {
          toJSON: vi.fn().mockReturnValue([newFileEntry]),
        },
      });

      mockInputPhase.mockResolvedValue(["content"]);

      await processSessionFiles({
        sessionId: "session-1",
        files: [{ name: "doc.pdf", size: 100, type: "application/pdf", dataUrl: "data:application/pdf;base64,xxx" }],
      });

      expect(mockInputPhase).toHaveBeenCalledTimes(1);
      expect(mockSaveSessionSetup).toHaveBeenCalledWith("session-1", expect.objectContaining({
        fileRegistry: [...existingRegistry, newFileEntry],
      }));
    });

    it("appends to undefined registry", async () => {
      mockLoadSessionSetup.mockReturnValue({
        skillName: "test-skill",
        skillmd: "# Skill",
        checks: [],
        scripts: [],
        regulationIds: [],
        steps: [],
      });

      mockCreatePipelineContext.mockReturnValue({
        skill: { name: "test-skill", checks: [], scripts: [], regulationIds: [], skillmd: "# Skill" },
        files: { toJSON: vi.fn().mockReturnValue([{ filename: "doc.pdf" }]) },
      });

      mockInputPhase.mockResolvedValue(["content"]);

      await processSessionFiles({
        sessionId: "session-1",
        files: [{ name: "doc.pdf", size: 100, type: "application/pdf", dataUrl: "data:base64," }],
      });

      expect(mockSaveSessionSetup).toHaveBeenCalledWith("session-1", expect.objectContaining({
        fileRegistry: expect.arrayContaining([{ filename: "doc.pdf" }]),
      }));
    });
  });
});
