import { initSession } from "../loading/phases/init-phase";
import { inputPhase } from "../loading/phases/input-phase";
import { skillGenPhase } from "../loading/phases/skill-gen-phase";
import { generateStepsFromChecks } from "../loading/generate-steps";
import { createPipelineContext, restoreContext } from "../pipeline/pipeline-context";
import { generateCorrelationId } from "../pipeline/errors";
import { saveSessionSetup, loadSessionSetup } from "../shared/memory/repository";
import { logPipeline } from "../pipeline/logger";

export interface SetupSessionParams {
  skillName?: string;
  sessionId: string;
  tenantId?: string;
  userId?: string;
  userEmail?: string;
  files?: { name: string; size: number; type: string; dataUrl?: string }[];
  message?: string;
  lessonOverrides?: string[];
}

// ── Phase 1: Load SKILL.md + create context + generate steps + persist ──

export async function setupSkill(
  sessionId: string,
  skillName: string,
  options?: { tenantId?: string; userId?: string; userEmail?: string }
): Promise<string> {
  const correlationId = generateCorrelationId();
  logPipeline(`=== SETUP-SKILL START === skill="${skillName}" session="${sessionId}"`);

  const { skill } = await initSession(skillName, sessionId, options?.tenantId, options?.userId, options?.userEmail);

  const ctx = createPipelineContext(
    skill.name, skill.skillmd, sessionId, correlationId,
    skill.checks, skill.scripts, skill.regulationIds,
  );

  if (skill.checks.length > 0) {
    ctx.skill.skillmd += "\n\n> Auto-generated by clausr.ai";
  }

  const steps = generateStepsFromChecks(ctx.skill.checks, ctx.skill.regulationIds);
  logPipeline(`[SETUP-SKILL] ${steps.length} step(s) from ${ctx.skill.checks.length} check(s)`);

  saveSessionSetup(sessionId, {
    skillName: ctx.skill.name,
    skillmd: ctx.skill.skillmd,
    checks: ctx.skill.checks,
    scripts: ctx.skill.scripts,
    regulationIds: ctx.skill.regulationIds,
    steps,
    fileRegistry: [],
  });

  logPipeline(`=== SETUP-SKILL DONE === session="${sessionId}"`);
  return correlationId;
}

// ── Phase 2: Process files through extractors + update persisted file registry ──

export interface ProcessFilesParams {
  sessionId: string;
  files: { name: string; size: number; type: string; dataUrl?: string }[];
}

export async function processSessionFiles(params: ProcessFilesParams): Promise<void> {
  const { sessionId, files } = params;
  if (!files || files.length === 0) return;

  const setup = loadSessionSetup(sessionId);
  if (!setup) {
    logPipeline(`[PROCESS-FILES] no setup found for session="${sessionId}" — call setupSkill first`);
    return;
  }

  logPipeline(`=== PROCESS-FILES START === session="${sessionId}" files=${files.length}`);
  const correlationId = generateCorrelationId();

  const ctx = createPipelineContext(
    setup.skillName, setup.skillmd, sessionId, correlationId,
    setup.checks, setup.scripts, setup.regulationIds,
  );

  await inputPhase(ctx, { files, sessionId });

  const existingRegistry = setup.fileRegistry ?? [];
  const updatedRegistry = [...existingRegistry, ...ctx.files.toJSON()];

  saveSessionSetup(sessionId, {
    skillName: setup.skillName,
    skillmd: setup.skillmd,
    checks: setup.checks,
    scripts: setup.scripts,
    regulationIds: setup.regulationIds,
    steps: setup.steps,
    fileRegistry: updatedRegistry,
  });

  logPipeline(`=== PROCESS-FILES DONE === session="${sessionId}" added=${files.length} total=${updatedRegistry.length}`);
}

// ── Original atomic setupSession (unchanged, uses same internal phases) ──

export async function setupSession(params: SetupSessionParams): Promise<{ correlationId: string; autoSkillUsage?: { promptTokens: number; completionTokens: number } }> {
  const correlationId = generateCorrelationId();
  logPipeline(`=== SETUP START === skill="${params.skillName ?? "(auto)"}" session="${params.sessionId}"`);

  const { skill, isAutoSkill } = await initSession(params.skillName, params.sessionId, params.tenantId, params.userId, params.userEmail);

  const ctx = createPipelineContext(
    skill.name, skill.skillmd, params.sessionId, correlationId,
    skill.checks, skill.scripts, skill.regulationIds,
  );

  let fileTexts: string[] = [];
  if (params.files && params.files.length > 0) {
    logPipeline(`[SETUP] processing ${params.files.length} file(s)`);
    fileTexts = await inputPhase(ctx, { files: params.files, sessionId: params.sessionId });
  }

  let autoSkillUsage: { promptTokens: number; completionTokens: number } | undefined;
  if (isAutoSkill) {
    if (!params.message) throw new Error("Auto-skill requires a 'message' describing what to assess");
    logPipeline("[SETUP] generating auto-skill from user message + file texts");
    autoSkillUsage = await skillGenPhase(ctx, params.message, fileTexts);
  }

  if (params.lessonOverrides && params.lessonOverrides.length > 0) {
    const lessonBlock = params.lessonOverrides.map((t) => `- ${t}`).join("\n");
    ctx.skill.skillmd = ctx.skill.skillmd + "\n\n### Tenant Lessons\n" + lessonBlock;
    logPipeline(`[SETUP] merged ${params.lessonOverrides.length} lesson override(s)`);
  }

  const steps = generateStepsFromChecks(ctx.skill.checks, ctx.skill.regulationIds);
  logPipeline(`[SETUP] generated ${steps.length} step(s) from ${ctx.skill.checks.length} check(s)`);

  saveSessionSetup(params.sessionId, {
    skillName: ctx.skill.name,
    skillmd: ctx.skill.skillmd,
    checks: ctx.skill.checks,
    scripts: ctx.skill.scripts,
    regulationIds: ctx.skill.regulationIds,
    steps,
    fileRegistry: ctx.files.toJSON(),
  });

  logPipeline(`=== SETUP DONE === session="${params.sessionId}" cid=${correlationId}`);
  return { correlationId, autoSkillUsage };
}
