import { initSession } from "../loading/phases/init-phase";
import { inputPhase } from "../loading/phases/input-phase";
import { generateStepsFromChecks } from "../loading/generate-steps";
import { createPipelineContext, restoreContext } from "../pipeline/pipeline-context";
import { generateCorrelationId } from "../pipeline/errors";
import { saveSessionSetup, loadSessionSetup } from "../shared/memory/repository";
import { logPipeline } from "../pipeline/logger";

// ── Phase 1: Load SKILL.md + create context + generate steps + persist ──

export async function setupSkill(
  sessionId: string,
  skillName: string,
  options?: { tenantId?: string; userId?: string; userEmail?: string }
): Promise<string> {
  const correlationId = generateCorrelationId();
  logPipeline(`=== SETUP-SKILL START === skill="${skillName}" session="${sessionId}"`);

  const { skill } = await initSession(skillName, sessionId, options?.tenantId, options?.userId, options?.userEmail);

  const ctx = createPipelineContext(
    skill.name, skill.skillmd, sessionId, correlationId,
    skill.checks, skill.scripts, skill.regulationIds,
  );

  if (skill.checks.length > 0) {
    ctx.skill.skillmd += "\n\n> Auto-generated by clausr.ai";
  }

  const steps = generateStepsFromChecks(ctx.skill.checks, ctx.skill.regulationIds);
  logPipeline(`[SETUP-SKILL] ${steps.length} step(s) from ${ctx.skill.checks.length} check(s)`);

  saveSessionSetup(sessionId, {
    skillName: ctx.skill.name,
    skillmd: ctx.skill.skillmd,
    checks: ctx.skill.checks,
    scripts: ctx.skill.scripts,
    regulationIds: ctx.skill.regulationIds,
    steps,
    fileRegistry: [],
  });

  logPipeline(`=== SETUP-SKILL DONE === session="${sessionId}"`);
  return correlationId;
}

// ── Phase 2: Process files through extractors + update persisted file registry ──

export interface ProcessFilesParams {
  sessionId: string;
  files: { name: string; size: number; type: string; dataUrl?: string }[];
}

export async function processSessionFiles(params: ProcessFilesParams): Promise<void> {
  const { sessionId, files } = params;
  if (!files || files.length === 0) return;

  const setup = loadSessionSetup(sessionId);
  if (!setup) {
    logPipeline(`[PROCESS-FILES] no setup found for session="${sessionId}" — call setupSkill first`);
    return;
  }

  logPipeline(`=== PROCESS-FILES START === session="${sessionId}" files=${files.length}`);
  const correlationId = generateCorrelationId();

  const ctx = createPipelineContext(
    setup.skillName, setup.skillmd, sessionId, correlationId,
    setup.checks, setup.scripts, setup.regulationIds,
  );

  await inputPhase(ctx, { files, sessionId });

  const existingRegistry = setup.fileRegistry ?? [];
  const updatedRegistry = [...existingRegistry, ...ctx.files.toJSON()];

  saveSessionSetup(sessionId, {
    skillName: setup.skillName,
    skillmd: setup.skillmd,
    checks: setup.checks,
    scripts: setup.scripts,
    regulationIds: setup.regulationIds,
    steps: setup.steps,
    fileRegistry: updatedRegistry,
  });
}


